language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: pT5actgluU3yMiWJ3E6I71mh8k2GULACsktvwHMUbWvMjkyVJfrsxuU3PDCnC/gzzrVvhT3OlrYbD6+UoYnuLzR9cnnTFNh6yZdXD19oGCzjJQvLzsH+XRQWGwQvHrzOFKyU05FQC1eNf53tHUH51O+EL2qXk/VONNKiPAqshk8jaf4X2rADh93HIY42D0d9XtYH7abVsxekAExEN7l9Hy63W4bSQyiXcyJFmHR+sxXwQie72aZbD9zfIZYJGVBgn8e0HqLlanALzkc4nYoj4IP0B3Fm+tAH3tPkN/+vCRn7kfy38nTOxbZTdaIX2NHBjA19kRI5PveOkKz7BCI2R+JeUWC/tF1aAmNvY87mI6QfNcoCyS9QbcVoz5JZguW7PcpHfiD0jCLocv81d1NV2EKmSdelsjtx/75kFW2ZFWZ9miVeM+c0zTJX21nd0nq+t7csWS9S6VfQlaFG/w+63taYOqIhYlC0zjiWWSXCQjwYc2JZDYK4JqCUc8obeHqzcjBWUpqDAHWMTvSI3auRhCRptfNOvrieQjZM4vQqLqPqHFUySgum6PGxqyUIpenXS5Xh8dUIzxVPV8NxLaXQwvjUT34DBZod9Fk9E++m3oYzRt45kCLbLUWVkO/6IeDblIliwxcgaD0chNh16ED+jCKPtSV44pPN4SNg6zJckDA=
    # FIREBASE_SECRET
    - secure: hLY71NffV3krFWqUvjBt6CpWQiaz4ltzzOBCtSYC/9VWMNsGssQ6bQmNRdICQEaSqwHWJfuESvsaJwJ+1DOg1qpQ4DE0jfX8bseXmKGVVQYp/Y5abVx8TVhilfMCuK4aNWN3O+fI/QA+3NhcfQvHM61THp7vdqmlVgIxAvT+jpfMMj99OP8TQOusCRmZxwmN9iHZQ01EVQaLNqkU7ZmAKnEJekk9U6x9jDkumhV42HGJpaZlm7XxZiTNNu5jlVe22rYGb0Uz2s7M4QGyT7uA1k8dlhacHxw4rvugLuQW27/gNHdVhg5Qi5gXVLZxVhiY0y7dO5Ry4KlVQhgxRPT1gPOLfxBE4DED+j5oDCYx8cZJBKBfrg0fv7CLooLAaYgEF2Kj02WRsFaAK++xZlMTUavQP9ArQH4xxPwJdjwMPW/rFPHL9czTKvwm6UKDOeswNCwuucE6P0nYx4ogPMcix/5D5sMqTGiFfhdcp/84YLZPMT98IBVze9FW344RQGc/YJmr59h/MOTdL+LUpRIIGOr/2wJWofsp45/ob7GlwqHasXMpRriBP4q7Btgjpl2+IROlISBwXVK3HWB30z6siGXu3SwzWYVxQhp7qnkAIhzVmBwx7KRW4B9twDDuGgROqGXhC/aZL47lY4C/y7zJn1+AGEUNfINBmAQRVJX/dmc=
