language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: Xw4yGByFeEIJNjV3yTpB3V3FpjS84BEJ4lVcyJ7UptMFdCgqqI+fgaYh+bBw5zlActjvtFvFnojFE9bH1ZfJaSG29NMf3x+6D32skrd118tC7RZ+pVfi18Jm/9cUnxfHm12IIz/0DUq/rDSZfD8zp8sITCX2QS+diLkYy01iTD5+BXCq4lH4WbQfixAdmbvb1WDkCUcCe/VKSZynbC1jEn/9FFGjpx+8Q5poL8DbYC6c9TKQjlbUvKq/ck3RCTw6h+UWDkowfzU8nlevR/qHMnx+NRfnwSrpuKtACxyhJ/80wc/t1QC6WmqkU4H5oBYJQTI0Ceglo0gr7/yIi3j8EE0TkLCzNuv3sq2aX4XeOTD+5nhK73aVrLqXu25sdIBDjItvdhG+mhlSr1htcjKL5zxboGBXtW+CXvg9zOTsxi/r0W4uydFvo5uiCaE0/RMA2Kf5m05OStZWnwZ/IWC0x4mDJg3GDWBwx5ZpPaAdBZESTFydB6xdKK1UrOrcciHo2sd1/5M91hDAh64on/mzCNSM1tK3uRbYpgD5J1F3x21o295PWdR8dLZodRT2YxIKuHE2dx8pUBSoD1eE0ipuGhvjfkMnpArKQjqVxof1e3eoVfbdT7HxB5Rxhbz6yUaqD1StCz6rlnflNe/j0OseoZFl0htT2TZdJJECy5dOWA0=
    # FIREBASE_SECRET
    - secure: axFOOXA/4vCm/nFgyieHLuHOP8HJsT7KYk172UiIMdQukDQCD31nhg4pqlkjTD3bPZGduVfv3fOySuJueOvvlNZG1R1cgjbzFsR543hqelA94nEDEDCvt/WR2jLokin23dObG+CdyhlYLDDFT7PHsQl9wdtCHDazXsx0zOkiTCBBQImy6mNYgWdN3PbtBNvkUXX5oVY8uc7YH+PVkxHN7mkbhTGbGJbleCYxJ13C+aWSS7nRbDbZt1Djr/tJM2hRoRwbwr7n3Ym9q8UCrxI+oK5jCx56kEAhqJpg/Ugy7Ceo0ZtSxlxQYOcfts/EIh5Y515UuEUsSvDZIzJ1AGDLvRYaG7VrRxqfzVsSQ/8nesty4HR+vyucJ2h8Gnsri3R4SYOjGdjcQoEwHLucA0dbvKXTZuncaLvh5mH639pVwhvMNGseQ6wsJAuLgwRNBc5t/xs+yGhyDHplfWw7YmCdxiqKGDjCiOYfJEz9LoKevZh810m7W36WoJxHEekrkPlTKKhBfLjGzn+eFd16fSQRh/h8UT8iIqZP9UQuy8RGpx4jOkhHW+//DZqCi7kIXghzDq6DSbW0u5UIwOiFvS1Rng7cz5IAayRKOnWdY/rf517m8o9UXVChQEateCuEAPVWAC13iwwz2LUlGMzUtbRZ/Qm2egFqt842BDMn0X2ITH8=
